[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["DanyloSarvasNulp <91377012+DanyloSarvasNulp@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Flask = "^2.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "private-repo"
url = "https://url"
default = true

[[tool.poetry.source]]
name = "private-repo2"
url = "https://url2"
