"""add models

Revision ID: 094a561f7f56
Revises: b7db1101448e
Create Date: 2021-11-22 09:10:56.868936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094a561f7f56'
down_revision = 'b7db1101448e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
