"""add models

Revision ID: 91a6dd664660
Revises: 094a561f7f56
Create Date: 2021-12-04 19:21:09.050757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a6dd664660'
down_revision = '094a561f7f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
